FROM node:18-alpine
WORKDIR /app
COPY . .

ARG ARG_ESE_URL
ARG ARG_ESE_PORT
ENV ESE_URL=${ARG_ESE_URL}
ENV ESE_PORT=${ARG_ESE_PORT}

ARG ARG_HTTP_PORT=8084
ARG ARG_HTTPS_PORT=8085
ENV LISTENING_HTTP_PORT=${ARG_HTTP_PORT}
ENV LISTENING_HTTPS_PORT=${ARG_HTTPS_PORT}

RUN npm install 

RUN npm run env

EXPOSE ${ARG_HTTP_PORT}

CMD npm start

